POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NWFhNzQzNzQ1NDhmOTM3ZTU4ZDE0YTYiLCJpYXQiOjE3MDU2Njk4MDJ9.UGKtPqh36VDyx4xIm89wqYkcDacbq5ryq7UUMvvlv7g

{
    "title": "blogBBB",
    "url": "url.com/BBB",
    "likes": 3
}