POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY1YmZhYmUzZmI3NmYxYzY3N2U3ZDA0MiIsImlhdCI6MTcwOTY2Njk0NH0.8oGNdEOQEKUOI4OHQ6qMM0EkwAMsishjmILVNbBuph4

{
    "title": "blogCCC",
    "url": "url.com/CCC",
    "likes": 3,
    "content": "#This is the content"
}