PUT http://localhost:3003/api/blogs/65f49eb3ab488eb69680055d
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY1ZjM0ZmZjZjM0YWU4YjI3NDVmZjQ0YiIsImlhdCI6MTcxMDUzMDIwOH0.QIv6HC8P6M8bmILnSQeKkGnNFjNGqQkFYzQNLNE4Nrc

{
    "likes": 1
}